### ISSUE TITLE
google shortlink not working

### ISSUE THREAD

**Issue by Zathras42** [solmoller/eversolar-monitor#12]
Went to download raspberry pi image using http://goo.gl/O41CVn
Error returned is:  this goo.gl shortlink has been disabled. It was found to be violating our Terms of Service. Click here and here for more information about our terms and policies respectively.

Can it be fixed please?

**Comment by solmoller** [comment]
Hi there,

Strange, it works for me, and I see some activity in the stats on the log. Anyway, if the problem persists, try this link: https://www.dropbox.com/s/zgh74n3zwzgd3l2/Eversolar_rpi_2015.zip?dl=0

Good luck!

Henrik

**Comment by Zathras42** [comment]
Thanks Henrik.
The dropbox link works ok :)
Cheers,
Rick

**Comment by solmoller** [comment]
ok , closing
