### ISSUE TITLE
root pw

### ISSUE THREAD

**Issue by Zathras42** [solmoller/eversolar-monitor#15]
Hi,
What is the root password for the RPi image, please?
Thanks,
Rick

**Comment by wotid** [comment]
I've not tried running eversolar-monitor from the supplied image but the standard RPi images don't have a root user, where root privileges are needed you can use sudo in front of the command.

If you want to create a root user / log in as root then try:

sudo passwd root

and selected your own password for the root user.

**Comment by Zathras42** [comment]
Thanks.
Wanted to know just in case using sudo to load a new USB wifi driver didn't work.

**Comment by solmoller** [comment]
Closed
