### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by ronneman** [solmoller/eversolar-monitor#19]
Hi all,

Since a few weeks I have an issue that the "Power right now" and "Max power today" are always 0. All the other attributes AC / PV & inverter details are present and updated including "Total energy today". However I do think I am missing one string in the inverter details. I have a TL2000-20 with 2 strings.

My cable is a standard network cable with one end changed according to the specs of the introduction page. A USB serial converter and a Rasperry PI B. As i said it did work for a couple of years with all values but suddenly is missing some data.

Any clues on what it might be? 

Best regards,
Ron

**Comment by solmoller** [comment]
No. Pls check, if no other values intermittent fail. If it is only that one
value, then you can rule out cabling and start worrying about your system:
 maybe the system actually have production failures. Is it just one of the
two inverters with this behaviour?

BR Henrik

Den 29/05/2017 7.46 AM skrev "ronneman" <notifications@github.com>:

**Comment by ronneman** [comment]
No the values are always 0. I have only one inverter but with 2 input strings from the panels.

![image](https://cloud.githubusercontent.com/assets/18702036/26538553/da0d1886-4447-11e7-9f39-1b53aca63861.png)

**Comment by ronneman** [comment]
I shutoff AC & DC power to the inverter, reconnected the strings, turned back the power on and it is working again. The power and max power are listed again.

Thanks for pointing me to the system. Was assuming it was my bad cable making skills ;)
