### ISSUE TITLE
Wiki hardware page: image EversolarDatalogger.jpg is gone

### ISSUE THREAD

**Issue by jpluimers** [solmoller/eversolar-monitor#20]
At the wiki page https://github.com/solmoller/eversolar-monitor/blob/wiki/Hardware.md the https://dl.dropbox.com/u/13405211/EversolarDatalogger.jpg image is gone, just as the underlying image https://camo.githubusercontent.com/22c1183b74b2ed12a6872eeb283b8d4a8008a8de/68747470733a2f2f646c2e64726f70626f782e636f6d2f752f31333430353231312f45766572736f6c6172446174616c6f676765722e6a7067

Since I've no idea what the image should represent, I cannot fix it myself and send a pull-request.

Please either repair, or point me to a URL so I can fix and create a pull-request.

**Comment by solmoller** [comment]
I've removed the image, the user that had taken a picture has removed it from his dropbox. 

I have replaced it with a more generic suggestion for solving the wiring problem
