### ISSUE TITLE
Image not working on Raspberry 3 or Zero W

### ISSUE THREAD

**Issue by jessgade** [solmoller/eversolar-monitor#25]
Hi

I've downloaded the image and tried it on both a raspberry 3 and a zero wireless - but my screen remains blank. The Zero blinks 7 consecutive times. 

I havent got any of the older models.
Anyone tried it with a version3 and/or a zero with success?

Regards
Jess

EDIT: I've got it working by using the Raspbian image and installing the software via the guide - So one happy camper here.

**Comment by solmoller** [comment]
Unless other have the same problem I'll close this for now. I think it's probably as the base code in the image is old, so I'll need to opgrade and update the operating system. It's a pain, as I then have to shrink the image below 3,8 GB manually. Unless someone knows a nice tool ?
