### ISSUE TITLE
db.sqlite size discussion

### ISSUE THREAD

**Issue by Steve9R** [solmoller/eversolar-monitor#29]
Discussion / Suggestion

my sqlite db is currently 

-rw-r--r-- 1 root root 124765184 Jan 21 09:08 db.sqlite

124mb.. should there be a process for trimming it over time to keep it manageable.. as i can see it just growing and growing and eventually filling my pi storage..I know i can replace it with the blank one but perhaps even gzipping off to archive say every 12months and starting clean every year to avoid corruptions? and huge sizes ?

Steve

**Comment by solmoller** [comment]
Closing
