### ISSUE TITLE
Wrong values reported (ZL2000S)

### ISSUE THREAD

**Issue by RRJohansen** [solmoller/eversolar-monitor#40]
I followed the excellent guide (thank you very much!) and after some light trouble shooting I got it working. Or so I thought!
I'm seeing wrong values reported in every field (see attached screenshot).

Looking at the inverter directly shows current production of ~70W and Today~2kWh.

Is it possible to directly see the returned string and decode it manually? 
Or how should one proceed?

Thank you in advance. 

  
![image](https://user-images.githubusercontent.com/26406240/54295657-c6e6fc80-45b3-11e9-9004-da0291b7de07.png)

**Comment by solmoller** [comment]
Interesting! Are you sure you have the right settings for strings? There
are two almost identical protokols...

ons. d. 13. mar. 2019 17.21 skrev RRJohansen <notifications@github.com>:

**Comment by RRJohansen** [comment]
You were right. Changing strings to 2 have fixed it. Thank you. 
I was confused by the following text in the guide (https://github.com/solmoller/eversolar-monitor/blob/wiki/Software_installation.md):
"Strings is one for Eversolar TL 2000 and below, it is 2 for TL 3000 and above." ZL2000S is different than TL2000 :-) 

Everything seem to work now. Thank you again.
![image](https://user-images.githubusercontent.com/26406240/54474383-422ef500-47e4-11e9-83ff-d5abf00053af.png)

**Comment by solmoller** [comment]
Thanks for the feedback, I'm changing the ini file and documentation now to reflect the ZL2000S
