### ISSUE TITLE
Webserver only showing log window

### ISSUE THREAD

**Issue by Reneke43** [solmoller/eversolar-monitor#43]
I've had this problem for quite some time now. I didn't look into it, because the values are pushed to my Domoticz server correctly. But I would like to know what's happening here. I only see the log window and no live output.
<img width="806" alt="Schermafbeelding 2019-10-25 om 21 00 29" src="https://user-images.githubusercontent.com/19175257/67597264-05a87c00-f76b-11e9-9ce9-b74160db2da3.png">

**Comment by solmoller** [comment]
Interesting, I've just checked mine, and it works fine. It appears though, that it loads the log first. Try disabling the log display and see if the other parts load..

**Comment by Reneke43** [comment]
Uhm, and how/where would I do that? 😳
In the mean time I've tried Safari, Chrome and Firefox on my Mac
and IE, Edge, Chrome and Firefox on Windows; I think it's fair to conclude it's not a browser/OS related issue...

**Comment by solmoller** [comment]
Sry for the delay. Go into the code and comment out the log display.

**Comment by kiekerjan** [comment]
I got the same issue. In my case it was solved by adding a line in function register_inverter:
```
my $serial_number = unpack( "Z*", $serial_num_response );
$serial_number =~ s/\W//g;
```
(I added the second line, the first is for location reference
Thanks to issue #10

**Comment by Reneke43** [comment]
I just saw your comment kiekerjan. I just found out the same after reinstalling the script on a clean Ubuntu server. To prevent a lot of writes to my SSD disk, I disabled the log. The first time I did this on my RPi, I didn't check the web interface. So when I did check it a few weeks later, I didn't connect the dots anymore.
However, I'm no expert at Perl scripting. Is there a way to solve this and get the values for the web view somewhere else? Straight from the variables in stead of the database/log?

**Comment by solmoller** [comment]
do you have a db.sqlite file at all? That may be the culprit

**Comment by Reneke43** [comment]
Yep, dB.sqlite is present and is being updated, as long as I have set “log = 1” in the ini file. As soon as I set “log = 0”, the webinterface changes.

**Comment by kiekerjan** [comment]
@Reneke43 I solved this in the referenced pull request. Unfortunately, It has become quite an involved change, including some database juggling and what not. If you only want that change, you'll still need some perl knowledge. But, I did not have that either when I started this so it shouldn't be too difficult.
I have tested this for about 10 days, and it seems to be working as expected.
