### ISSUE TITLE
Configuring for Eversolar Evershine TL5000

### ISSUE THREAD

**Issue by cr750** [solmoller/eversolar-monitor#45]
I have an old version of the code (v0.13) working on a PC using eth2ser.
I am attempting to build a Raspberry Pi to take its place.
(I'm an idiot)

**Comment by solmoller** [comment]
What is the problem?

**Comment by solmoller** [comment]
Are you using the Raspberry image?

**Comment by cr750** [comment]
Hi Henrik,I didn't have logging to DB enabled. A silly mistake on my behalf.I use my own Linux PC web server to run the Perl logger for myself.I'm using a Pi for my father's logger.Regards,PhillSent from my Samsung Mobile on the Telstra Mobile Network
-------- Original message --------From: Henrik Møller Jørgensen <notifications@github.com> Date: 13/1/20  07:33  (GMT+10:00) To: solmoller/eversolar-monitor <eversolar-monitor@noreply.github.com> Cc: cr750 <phill.glasson@bigpond.com>, Author <author@noreply.github.com> Subject: Re: [solmoller/eversolar-monitor] Configuring for Eversolar Evershine TL5000 (#45) Are you using the Raspberry image?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/solmoller/eversolar-monitor/issues/45?email_source=notifications\u0026email_token=AOH4ASPHFU2RTAELUZ44FCLQ5N5CXA5CNFSM4KFPSDR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIXDQGQ#issuecomment-573454362",
"url": "https://github.com/solmoller/eversolar-monitor/issues/45?email_source=notifications\u0026email_token=AOH4ASPHFU2RTAELUZ44FCLQ5N5CXA5CNFSM4KFPSDR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIXDQGQ#issuecomment-573454362",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by solmoller** [comment]
Closing, issue is reported in other instances
