### ISSUE TITLE
Support for web page scraping

### ISSUE THREAD

**Issue by cr750** [solmoller/eversolar-monitor#46]
Hi, I'm installing the monitor on a Pi, and have it working with eth2ser on a TL5000 inverter.
My father has a small eversolar (sorry, don't know the model) that has a web page, /home.cgi, which provides a limited set of data.
I have written some perl to gather data from the page, but I'm having difficulty figuring out how to integrate into eversolar-monitor.

If I provide the screen scraping code, could you integrate it with the main branch? I'm happy to test at any time.
[exampleData.txt](https://github.com/solmoller/eversolar-monitor/files/4049048/exampleData.txt)

[home.php.txt](https://github.com/solmoller/eversolar-monitor/files/4049049/home.php.txt)
[getWebData.pl.txt](https://github.com/solmoller/eversolar-monitor/files/4049050/getWebData.pl.txt)

**Comment by solmoller** [comment]
Looks promising, bit why not connect directly to the unknown Eversolar inverter through serial?

**Comment by cr750** [comment]
Hi Henrik,The inverter is in a difficult location for serial cabling, but it does have a Wi-Fi connection from which /home.cgi is available. The Wi-Fi option allows me to configure the Pi, mail it to my 90 year old father, and all he has to do is plug in the Ethernet cable and the power cable.Regards,Phill.Sent from my Samsung Mobile on the Telstra Mobile Network
-------- Original message --------From: Henrik Møller Jørgensen <notifications@github.com> Date: 13/1/20  07:33  (GMT+10:00) To: solmoller/eversolar-monitor <eversolar-monitor@noreply.github.com> Cc: cr750 <phill.glasson@bigpond.com>, Author <author@noreply.github.com> Subject: Re: [solmoller/eversolar-monitor] Support for web page scraping (#46) Looks promising, bit why not connect directly to the unknown Eversolar inverter through serial?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/solmoller/eversolar-monitor/issues/46?email_source=notifications\u0026email_token=AOH4ASMYLKDL4GG2YROVR73Q5N47ZA5CNFSM4KFQORJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIXDPUY#issuecomment-573454291",
"url": "https://github.com/solmoller/eversolar-monitor/issues/46?email_source=notifications\u0026email_token=AOH4ASMYLKDL4GG2YROVR73Q5N47ZA5CNFSM4KFQORJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIXDPUY#issuecomment-573454291",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by solmoller** [comment]
This is getting old, sry

If the inverter is placed within wifi reach, then it should be possible to place a RPI with Wifi near it and connect through serial - or use a serial-wifi adapter, that is supported.

I can't support screen scraping, as I don't have access to an inverter that publishes a web page

BR henrik

**Comment by solmoller** [comment]
closed due to inactivity
