### ISSUE TITLE
Serial number can contain non ascii values

### ISSUE THREAD

**Issue by kiekerjan** [solmoller/eversolar-monitor#47]
Similar to issue #10 I got an issue where the serial number contains non-ascii characters.
I solved it by adding a line in function register_inverter:
```
my $serial_number = unpack( "Z*", $serial_num_response );
$serial_number =~ s/\W//g;
```
(I added the second line, the first is for location reference)

**Comment by solmoller** [comment]
Interesting, I'll look into this, when I am home and the sun is up. As far north as I live that is rare occation these days.
