### ISSUE TITLE
Log on web interface not showing last line in logfile

### ISSUE THREAD

**Issue by ronbuist** [solmoller/eversolar-monitor#52]
Hi all,

First of all: thanks for this wonderful project. My dad has a TL4000 inverter and was using a Zeversolar PMU in combination with the Zevercloud website. This worked reasonably well for quite some time albeit with some glitches, but somewhere last month it stopped working altogether. I had a Raspberry Pi B laying around, so I installed the Eversolar monitor software and got the right hardware. It's working very well and I'm using the JSON output to feed the data into a separate RPi 3B+ running Home Assistant.

There's just one weird thing I encountered: the web interface does not show the very last line of the log file (which should be shown as the very first in the web interface since the order of the lines is reversed). Even if I refresh the web page, I'm not getting the most recent log line in the web interface. I tried manually adding a line in /var/log/eversolar and after a refresh, everything was shown again except for the last line. Am I the only one seeing this?

I'm using a RPi B, have the latest version of Raspbian Lite installed on it and installed the Eversolar Monitor by following the Wiki page.

**Comment by solmoller** [comment]
Interesting, I haven't been able to test so far, but you can try debugging around database entry first - an SQL statement that returns latest line every minute or so from a command line should allow you to see if it's a display problem, and that is what I gather it is
