### ISSUE TITLE
RS485 to USB converter

### ISSUE THREAD

**Issue by tobiasnorbo** [solmoller/eversolar-monitor#71]
Hi,

I'm sorry, but I don't know, where else to ask this. Would this converter be sufficient? And in that case, how would you connect the wires of an RS485 cable?

https://raspberrypi.dk/produkt/industriel-usb-til-rs485-bidirectional-converter/

**Comment by solmoller** [comment]
That looks promising. Please let me know if it works

In addition, if you use a new rpi with current OS, i'd like to hear if the
installation procedure needs updating. The old sd card image is outdated.

I run on an updated RPI4, but the OS is highly modified for other purposes

BR Henrik

ons. 1. maj 2024 21.04 skrev tobiasnorbo ***@***.***>:

**Comment by solmoller** [comment]
That is in the WIKI

ons. 1. maj 2024 21.40 skrev tobiasnorbo ***@***.***>:

**Comment by tobiasnorbo** [comment]
I did something right and probably a lot wrong. I was not sure what to do with the USB setting in the ini file. Does it matter which port it goes into and what this setting is?Before restart I did get some numbers, but they were wrong. Den 1. maj 2024 kl. 21.44 skrev Henrik Møller Jørgensen ***@***.***>:﻿
That is in the WIKI



ons. 1. maj 2024 21.40 skrev tobiasnorbo ***@***.***>:

**Comment by tobiasnorbo** [comment]
I thought it added the screen shots. Here they are. 
![IMG_1369](https://github.com/solmoller/eversolar-monitor/assets/162321792/0ba3c56e-a87e-46f4-b2a7-c354f5de1bf5)
![IMG_1362](https://github.com/solmoller/eversolar-monitor/assets/162321792/f90c9097-3a08-4323-a6f5-a72cf6479c2a)
![IMG_1365](https://github.com/solmoller/eversolar-monitor/assets/162321792/02aae2e1-1d8a-4b22-9ff8-61626d41a8e0)
![IMG_1364](https://github.com/solmoller/eversolar-monitor/assets/162321792/84fde854-5f34-4788-a60e-ac82b2ae7bb7)

**Comment by solmoller** [comment]
Great!

Yes, latest version can do HA, and we have an open issue on limiting the
inverter

Good news: you can throttle the thing!

tors. 2. maj 2024 19.52 skrev tobiasnorbo ***@***.***>:

**Comment by tobiasnorbo** [comment]
That sounds great! I am looking forward to that addition, so we can help the grid, when there is too much solar power on it.

Do you have a link to some documentation on getting the data into HA? The Danish forum that the wiki links to is not available anymore.

**Comment by solmoller** [comment]
I just updated the Wiki, it's MQTT that does the trick

And as for throttling, I have other projects, so I doubt I'll find time. Maybe you can lend a hand?

I am also interested in hearing what you went through to install on modern RPI

BR

Henrik

**Comment by solmoller** [comment]
Throttling is #66  - so you used the image in an RPI2 with success?

**Comment by tobiasnorbo** [comment]
Thanks a lot. I will look into the wiki and get HA up and running.

I would be happy to contribute, but I'm not sure I will get it to work, since my coding skills are limited.

And yes, I succeeded in using the image for the RPI2, and to complete the hardware I successfully used:

The rs485 converter in question for this 'issue', and it worked perfectly. See link below.
http://www.waveshare.com/wiki/USB_TO_RS485

Other hardware used was:
RaspberryPi 2B from 2015
RasPiKey 16gb, I was concerned about the lifetime of the SD cards, so chose this eMMC module version of a SD card: https://www.uugear.com/doc/RasPiKey_UserManual.pdf

Thanks a lot for all the help

**Comment by tobiasnorbo** [comment]
Just a small update.

I am not able to install musquitto on the Raspbberry wheezy version, that is part of the img file. So I will need to backup the files and upgrade to a newer OS.

I will therefore suggest that the wiki explains, that it is suggested to run on a newer RPI and not use the img file if you want to use MQTT for HA integration.

Right now I run HA on a RPI5, and the eversolar script on RPI2. But I am considering to execute both on the RPI5, now that I am running into these problems.

**Comment by solmoller** [comment]
Thanks! I have updated the Wiki 

I did a crash installation on my RPI4, simply by adding modules as the perl script failed. 
I did not write down the work though..
