### ISSUE TITLE
Powering Rpi0 from inverter.

### ISSUE THREAD

**Issue by nagydavid** [solmoller/eversolar-monitor#72]
Hi @solmoller ,

Do you know, if we(I) could power an rpi0 from the inverter. I just would like to reduce the cabling, in my setup. I am asking because you r the one who knows the most on the inverter.

**Comment by solmoller** [comment]
That's a strong NO, RPI's use +5W of power. I can extract the comms card by simply pulling it out of my TL3000, and no electronics appears capable of sustaining one amp.
